export const hoursFilter = [
  { item: "6", idx: 0 },
  { item: "8", idx: 1 },
  { item: "10", idx: 2 },
  { item: "12", idx: 3 },
];
export const proximityFilter = [
  { item: "On Site", idx: 4 },
  { item: "Hybrid", idx: 5 },
  { item: "Fully Remote", idx: 6 },
  { item: "Remote", idx: 7 },
];
export const experienceFilter = [
  { item: "Junior/Entry", idx: 8 },
  { item: "Intermediate", idx: 9 },
  { item: "Senior level", idx: 10 },
  { item: "C-level", idx: 11 },
];

export const industriesArr = [
  "Education",
  "Technology",
  "Healthcare",
  "Finance",
  "Retail",
  "Manufacturing",
  "Hospitality",
  "Automotive",
  "Construction",
  "Energy",
  "Entertainment",
  "Food & Beverage",
  "Government",
  "Insurance",
  "Legal",
  "Logistics",
  "Media",
  "Mining",
  "Pharmaceuticals",
  "Real Estate",
  "Telecommunications",
  "Transportation",
  "Travel & Tourism",
  "Agriculture",
  "Aerospace",
  "Biotechnology",
  "Consulting",
  "Defense",
  "Electronics",
  "Fashion",
  "Human Resources",
  "Non-Profit",
  "Oil & Gas",
  "Public Relations",
  "Software Development",
  "Sports",
  "Utilities",
  "Water Management",
  "Renewable Energy",
  "Waste Management",
  "Cybersecurity",
  "Marine",
  "Aviation",
  "Interior Design",
  "E-commerce",
  "Advertising",
  "Architecture",
  "Environmental Services",
];
